// app/components/Navbar.vue
<template>
    <nav class="flex justify-between items-center border-b border-b-gray-300 px-10 py-1 bg-white z-30 font-dana font-medium sticky top-0">
        <div class="flex items-center gap-1 md:gap-10">
            <!-- Logo -->
            <NuxtLink to="/">
                <NuxtImg src="/logo.avif" width="75" height="75" format="avif" alt="Logo" preload />
            </NuxtLink>

            <!-- Category -->
            <button class="hidden md:flex items-center gap-1 text-main-100 text-lg">
                <Icon class="text-xl" name="solar:widget-2-outline" />
                دسته‌بندی‌ها
            </button>

            <!-- Search Box -->
            <div class="hidden md:block relative">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 ">
                    <Icon name="solar:magnifer-outline" />
                </div>
                <input type="text" id="input-group-1"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg w-full md:w-96 ps-10 p-2.5"
                    placeholder="جستجو...">
            </div>
        </div>
        <div class="flex items-center gap-4">
            <!-- System Mode -->
            <button class="p-2 text-main-100 border border-main-100 rounded-full flex cursor-pointer" aria-label="color_mode">
                <Icon class="text-2xl" name="solar:sun-2-outline" />
            </button>

            <!-- Register -->
            <button class="md:block px-4 py-2 text-main-100 rounded-lg border border-main-100 cursor-pointer" @click="$emit('openLogin')">ورود | ثبت‌نام</button>
        </div>
    </nav>
</template>

// components/custom/navbar-components/navbar.tsx
import { Button } from "@/components/ui/button"
import { Login, Search, ShoppingBag03Icon } from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"
import Image from "next/image"
import { ModeToggle } from "../mode-toggle"

function Navbar() {
    return (
        <nav className="flex items-center justify-between px-4 shadow bg-white/10 backdrop-blur-sm border border-white/20 rounded-full sticky top-5 z-50 mt-5 mx-20">
            <div className="flex items-center gap-4">
                <div className="relative w-16 h-16">
                    <Image src="/logo.avif" fill alt="Logo" />
                </div>

                <ul className="flex items-center gap-4 text-primary">
                    <li>دوره‌ها</li>
                    <li>مسیر یادگیری</li>
                    <li>مقالات</li>
                    <li>درباره‌ما</li>
                </ul>
            </div>

            <div className="flex items-center gap-2">
                <Button variant="outline" size="icon-lg" className="border-primary/50">
                    <HugeiconsIcon icon={Search} className="size-6 text-primary" />
                </Button>

                <ModeToggle />

                <Button variant="outline" size="icon-lg" className="border-primary/50">
                    <HugeiconsIcon icon={ShoppingBag03Icon} className="size-6 text-primary" />
                </Button>

                <Button size="lg">
                    <HugeiconsIcon icon={Login} className="size-5 rotate-180" />
                    ورود | ثبت‌نام
                </Button>
            </div>
        </nav>
    )
}

export default Navbar
